
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: say-hello
spec:
  strategy: 
    type: Recreate
  selector:
      matchLabels:
        app.kubernetes.io/name: say-hello
 
  template:
    metadata:
      name: say-hello
      labels:
        app: say-hello
        version: blue
    spec:
      containers:
      - name: say-hello-container
        image: senth542002/kubernetes-deployment:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: say-hello
---
apiVersion: v1
kind: Service 
metadata:
  name: say-hello
  labels:
    app: say-hello
spec:
  selector:
    app: say-hello
    version: blue
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
