
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: say-hello
  labels: 
    app: say-hello
spec:
  strategy: 
    type: Recreate
  selector:
    matchLabels: 
      app: say-hello
 
  template:
    metadata:
      labels: 
        app: say-hello

    spec:
      containers:
      - name: kubernetes-deployment
        image: senth542002/kubernetes-deployment:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: say-hello
---
apiVersion: v1
kind: Service 
metadata:
  name: say-hello
  labels:
    app: say-hello
spec:
  selector:
    app: say-hello
    version: blue
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
